name: Next.js Build CI

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun i

            - name: Migrate Prisma
              run: bunx prisma migrate deploy
              env:
                  ADMIN_EMAIL: example@example.com

            - name: Next build
              run: bun run build
